### ISSUE TITLE
Does not build on OpenBSD 7.0

### ISSUE THREAD

**Issue by kasak87** [kostya/sigar#12]
```
Fetching kostya-sigar-2.0.10.gem
Building native extensions. This could take a while...
ERROR:  Error installing kostya-sigar:
	ERROR: Failed to build gem native extension.

    current directory: /home/diaspora/.gem/ruby/2.6/gems/kostya-sigar-2.0.10/bindings/ruby
/usr/local/bin/ruby26 -I /usr/local/lib/ruby/2.6 -r ./siteconf20211208-95778-h7x7x4.rb extconf.rb
Ruby platform=x86_64-openbsd
checking for -lkvm... yes
rbsigar_generated.rx needs update
generating rbsigar_generated.rx
../../src/sigar.c -> sigar.c
../../src/sigar_cache.c -> sigar_cache.c
../../src/sigar_fileinfo.c -> sigar_fileinfo.c
../../src/sigar_format.c -> sigar_format.c
../../src/sigar_getline.c -> sigar_getline.c
../../src/sigar_ptql.c -> sigar_ptql.c
../../src/sigar_signal.c -> sigar_signal.c
../../src/sigar_util.c -> sigar_util.c
../../src/os/darwin/darwin_sigar.c -> darwin_sigar.c
creating Makefile

current directory: /home/diaspora/.gem/ruby/2.6/gems/kostya-sigar-2.0.10/bindings/ruby
make "DESTDIR=" clean

current directory: /home/diaspora/.gem/ruby/2.6/gems/kostya-sigar-2.0.10/bindings/ruby
make "DESTDIR="
compiling darwin_sigar.c
darwin_sigar.c:55:10: fatal error: 'sys/dkstat.h' file not found
#include <sys/dkstat.h>
         ^~~~~~~~~~~~~~
1 error generated.
*** Error 1 in /home/diaspora/.gem/ruby/2.6/gems/kostya-sigar-2.0.10/bindings/ruby (Makefile:245 'darwin_sigar.o': @ cc -I. -I/usr/local/inc...)

```

**Comment by kostya** [comment]
seems it was renamed to `dkstats.h`

```
git clone https://github.com/kostya/sigar.git
cd sigar
```

Try replace `#include <sys/dkstat.h>` with `#include <dkstats.h>` and run `rake build`.
If it not work, try remove this line and find what methods use this, if methods not needed we can just remove them.

**Comment by kasak87** [comment]
unfortunately, replacing sys/dkstat.h with dkstats.h just throw same error with "dkstats.h not found"
removing this line causes huge amount of errors:


compiling darwin_sigar.c
darwin_sigar.c:841:23: error: use of undeclared identifier 'CPUSTATES'
    cp_time_t cp_time[CPUSTATES];
                      ^
darwin_sigar.c:864:41: error: use of undeclared identifier 'CP_USER'
    cpu->user = SIGAR_TICK2MSEC(cp_time[CP_USER]);
                                        ^
darwin_sigar.c:865:41: error: use of undeclared identifier 'CP_NICE'
    cpu->nice = SIGAR_TICK2MSEC(cp_time[CP_NICE]);
                                        ^
darwin_sigar.c:866:41: error: use of undeclared identifier 'CP_SYS'
    cpu->sys  = SIGAR_TICK2MSEC(cp_time[CP_SYS]);
                                        ^
darwin_sigar.c:867:41: error: use of undeclared identifier 'CP_IDLE'
    cpu->idle = SIGAR_TICK2MSEC(cp_time[CP_IDLE]);
                                        ^
darwin_sigar.c:869:40: error: use of undeclared identifier 'CP_INTR'
    cpu->irq = SIGAR_TICK2MSEC(cp_time[CP_INTR]);
                                       ^
darwin_sigar.c:1079:21: error: no member named 'kp_eproc' in 'struct kinfo_proc'
        if (proc[i].KI_FLAG & P_SYSTEM) {
            ~~~~~~~ ^
darwin_sigar.c:226:17: note: expanded from macro 'KI_FLAG'
#define KI_FLAG kp_eproc.e_flag
                ^
darwin_sigar.c:1079:31: error: use of undeclared identifier 'P_SYSTEM'
        if (proc[i].KI_FLAG & P_SYSTEM) {
                              ^
darwin_sigar.c:1082:21: error: no member named 'kp_proc' in 'struct kinfo_proc'
        if (proc[i].KI_PID == 0) {
            ~~~~~~~ ^
darwin_sigar.c:211:17: note: expanded from macro 'KI_PID'
#define KI_PID  kp_proc.p_pid
                ^
darwin_sigar.c:1086:54: error: no member named 'kp_proc' in 'struct kinfo_proc'
        proclist->data[proclist->number++] = proc[i].KI_PID;
                                             ~~~~~~~ ^
darwin_sigar.c:211:17: note: expanded from macro 'KI_PID'
#define KI_PID  kp_proc.p_pid
                ^
darwin_sigar.c:1117:29: error: use of undeclared identifier 'KERN_PROC2'
    int mib[] = { CTL_KERN, KERN_PROC2, KERN_PROC_PID, 0, sizeof(*sigar->pinfo), 1 };
                            ^
darwin_sigar.c:1117:65: error: invalid application of 'sizeof' to an incomplete type 'bsd_pinfo_t' (aka 'struct kinfo_proc2')
    int mib[] = { CTL_KERN, KERN_PROC2, KERN_PROC_PID, 0, sizeof(*sigar->pinfo), 1 };
                                                                ^~~~~~~~~~~~~~~
../../src/os/darwin/sigar_os.h:49:16: note: forward declaration of 'struct kinfo_proc2'
typedef struct kinfo_proc2 bsd_pinfo_t;
               ^
darwin_sigar.c:1121:24: error: invalid application of 'sizeof' to an incomplete type 'bsd_pinfo_t' (aka 'struct kinfo_proc2')
    size_t len = sizeof(*sigar->pinfo);
                       ^~~~~~~~~~~~~~~
../../src/os/darwin/sigar_os.h:49:16: note: forward declaration of 'struct kinfo_proc2'
typedef struct kinfo_proc2 bsd_pinfo_t;
               ^
darwin_sigar.c:1138:21: error: invalid application of 'sizeof' to an incomplete type 'int []'
    if (sysctl(mib, NMIB(mib), sigar->pinfo, &len, NULL, 0) < 0) {
                    ^~~~~~~~~
darwin_sigar.c:114:26: note: expanded from macro 'NMIB'
#define NMIB(mib) (sizeof(mib)/sizeof(mib[0]))
                         ^~~~~
darwin_sigar.c:1298:15: error: incomplete definition of type 'struct kinfo_proc2'
        (pinfo->p_vm_tsize + pinfo->p_vm_dsize + pinfo->p_vm_ssize) * sigar->pagesize;
         ~~~~~^
../../src/os/darwin/sigar_os.h:49:16: note: forward declaration of 'struct kinfo_proc2'
typedef struct kinfo_proc2 bsd_pinfo_t;
               ^
darwin_sigar.c:1298:35: error: incomplete definition of type 'struct kinfo_proc2'
        (pinfo->p_vm_tsize + pinfo->p_vm_dsize + pinfo->p_vm_ssize) * sigar->pagesize;
                             ~~~~~^
../../src/os/darwin/sigar_os.h:49:16: note: forward declaration of 'struct kinfo_proc2'
typedef struct kinfo_proc2 bsd_pinfo_t;
               ^
darwin_sigar.c:1298:55: error: incomplete definition of type 'struct kinfo_proc2'
        (pinfo->p_vm_tsize + pinfo->p_vm_dsize + pinfo->p_vm_ssize) * sigar->pagesize;
                                                 ~~~~~^
../../src/os/darwin/sigar_os.h:49:16: note: forward declaration of 'struct kinfo_proc2'
typedef struct kinfo_proc2 bsd_pinfo_t;
               ^
darwin_sigar.c:1300:30: error: incomplete definition of type 'struct kinfo_proc2'
    procmem->resident = pinfo->p_vm_rssize * sigar->pagesize;
                        ~~~~~^
../../src/os/darwin/sigar_os.h:49:16: note: forward declaration of 'struct kinfo_proc2'
typedef struct kinfo_proc2 bsd_pinfo_t;
               ^
darwin_sigar.c:1304:34: error: incomplete definition of type 'struct kinfo_proc2'
    procmem->minor_faults = pinfo->p_uru_minflt;
                            ~~~~~^
../../src/os/darwin/sigar_os.h:49:16: note: forward declaration of 'struct kinfo_proc2'
typedef struct kinfo_proc2 bsd_pinfo_t;
               ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
*** Error 1 in /home/diaspora/.gem/ruby/2.6/gems/kostya-sigar-2.0.8/bindings/ruby (Makefile:245 'darwin_sigar.o': @ cc -I. -I/usr/local/incl...)
Failed to make
rake aborted!
LocalJumpError: break from proc-closure
/home/diaspora/.gem/ruby/2.6/gems/kostya-sigar-2.0.8/Rakefile:63:in `block in <top (required)>'
/usr/local/bin/rake26:23:in `load'
/usr/local/bin/rake26:23:in `<main>'
Tasks: TOP => build
(See full trace by running task with --trace)

**Comment by kasak87** [comment]
as i can see, openbsd guys changed dkstat.h to sched.h [https://marc.info/?l=openbsd-tech&m=140999793929262&w=2](https://marc.info/?l=openbsd-tech&m=140999793929262&w=2)

But changing this, did not fix the build, just removed some errors

compiling darwin_sigar.c
darwin_sigar.c:1080:21: error: no member named 'kp_eproc' in 'struct kinfo_proc'
        if (proc[i].KI_FLAG & P_SYSTEM) {
            ~~~~~~~ ^
darwin_sigar.c:227:17: note: expanded from macro 'KI_FLAG'
#define KI_FLAG kp_eproc.e_flag
                ^
darwin_sigar.c:1080:31: error: use of undeclared identifier 'P_SYSTEM'
        if (proc[i].KI_FLAG & P_SYSTEM) {
                              ^
darwin_sigar.c:1083:21: error: no member named 'kp_proc' in 'struct kinfo_proc'
        if (proc[i].KI_PID == 0) {
            ~~~~~~~ ^
darwin_sigar.c:212:17: note: expanded from macro 'KI_PID'
#define KI_PID  kp_proc.p_pid
                ^
darwin_sigar.c:1087:54: error: no member named 'kp_proc' in 'struct kinfo_proc'
        proclist->data[proclist->number++] = proc[i].KI_PID;
                                             ~~~~~~~ ^
darwin_sigar.c:212:17: note: expanded from macro 'KI_PID'
#define KI_PID  kp_proc.p_pid
                ^
darwin_sigar.c:1118:29: error: use of undeclared identifier 'KERN_PROC2'
    int mib[] = { CTL_KERN, KERN_PROC2, KERN_PROC_PID, 0, sizeof(*sigar->pinfo), 1 };
                            ^
darwin_sigar.c:1118:65: error: invalid application of 'sizeof' to an incomplete type 'bsd_pinfo_t' (aka 'struct kinfo_proc2')
    int mib[] = { CTL_KERN, KERN_PROC2, KERN_PROC_PID, 0, sizeof(*sigar->pinfo), 1 };
                                                                ^~~~~~~~~~~~~~~
../../src/os/darwin/sigar_os.h:49:16: note: forward declaration of 'struct kinfo_proc2'
typedef struct kinfo_proc2 bsd_pinfo_t;
               ^
darwin_sigar.c:1122:24: error: invalid application of 'sizeof' to an incomplete type 'bsd_pinfo_t' (aka 'struct kinfo_proc2')
    size_t len = sizeof(*sigar->pinfo);
                       ^~~~~~~~~~~~~~~
../../src/os/darwin/sigar_os.h:49:16: note: forward declaration of 'struct kinfo_proc2'
typedef struct kinfo_proc2 bsd_pinfo_t;
               ^
darwin_sigar.c:1139:21: error: invalid application of 'sizeof' to an incomplete type 'int []'
    if (sysctl(mib, NMIB(mib), sigar->pinfo, &len, NULL, 0) < 0) {
                    ^~~~~~~~~
darwin_sigar.c:115:26: note: expanded from macro 'NMIB'
#define NMIB(mib) (sizeof(mib)/sizeof(mib[0]))
                         ^~~~~
darwin_sigar.c:1299:15: error: incomplete definition of type 'struct kinfo_proc2'
        (pinfo->p_vm_tsize + pinfo->p_vm_dsize + pinfo->p_vm_ssize) * sigar->pagesize;
         ~~~~~^
../../src/os/darwin/sigar_os.h:49:16: note: forward declaration of 'struct kinfo_proc2'
typedef struct kinfo_proc2 bsd_pinfo_t;
               ^
darwin_sigar.c:1299:35: error: incomplete definition of type 'struct kinfo_proc2'
        (pinfo->p_vm_tsize + pinfo->p_vm_dsize + pinfo->p_vm_ssize) * sigar->pagesize;
                             ~~~~~^
../../src/os/darwin/sigar_os.h:49:16: note: forward declaration of 'struct kinfo_proc2'
typedef struct kinfo_proc2 bsd_pinfo_t;
               ^
darwin_sigar.c:1299:55: error: incomplete definition of type 'struct kinfo_proc2'
        (pinfo->p_vm_tsize + pinfo->p_vm_dsize + pinfo->p_vm_ssize) * sigar->pagesize;
                                                 ~~~~~^
../../src/os/darwin/sigar_os.h:49:16: note: forward declaration of 'struct kinfo_proc2'
typedef struct kinfo_proc2 bsd_pinfo_t;
               ^
darwin_sigar.c:1301:30: error: incomplete definition of type 'struct kinfo_proc2'
    procmem->resident = pinfo->p_vm_rssize * sigar->pagesize;
                        ~~~~~^
../../src/os/darwin/sigar_os.h:49:16: note: forward declaration of 'struct kinfo_proc2'
typedef struct kinfo_proc2 bsd_pinfo_t;
               ^
darwin_sigar.c:1305:34: error: incomplete definition of type 'struct kinfo_proc2'
    procmem->minor_faults = pinfo->p_uru_minflt;
                            ~~~~~^
../../src/os/darwin/sigar_os.h:49:16: note: forward declaration of 'struct kinfo_proc2'
typedef struct kinfo_proc2 bsd_pinfo_t;
               ^
darwin_sigar.c:1306:34: error: incomplete definition of type 'struct kinfo_proc2'
    procmem->major_faults = pinfo->p_uru_majflt;
                            ~~~~~^
../../src/os/darwin/sigar_os.h:49:16: note: forward declaration of 'struct kinfo_proc2'
typedef struct kinfo_proc2 bsd_pinfo_t;
               ^
darwin_sigar.c:1330:27: error: incomplete definition of type 'struct kinfo_proc2'
    proccred->uid  = pinfo->p_ruid;
                     ~~~~~^
../../src/os/darwin/sigar_os.h:49:16: note: forward declaration of 'struct kinfo_proc2'
typedef struct kinfo_proc2 bsd_pinfo_t;
               ^
darwin_sigar.c:1331:27: error: incomplete definition of type 'struct kinfo_proc2'
    proccred->gid  = pinfo->p_rgid;
                     ~~~~~^
../../src/os/darwin/sigar_os.h:49:16: note: forward declaration of 'struct kinfo_proc2'
typedef struct kinfo_proc2 bsd_pinfo_t;
               ^
darwin_sigar.c:1332:27: error: incomplete definition of type 'struct kinfo_proc2'
    proccred->euid = pinfo->p_uid;
                     ~~~~~^
../../src/os/darwin/sigar_os.h:49:16: note: forward declaration of 'struct kinfo_proc2'
typedef struct kinfo_proc2 bsd_pinfo_t;
               ^
darwin_sigar.c:1333:27: error: incomplete definition of type 'struct kinfo_proc2'
    proccred->egid = pinfo->p_gid;
                     ~~~~~^
../../src/os/darwin/sigar_os.h:49:16: note: forward declaration of 'struct kinfo_proc2'
typedef struct kinfo_proc2 bsd_pinfo_t;
               ^
darwin_sigar.c:1456:28: error: incomplete definition of type 'struct kinfo_proc2'
    proctime->user  = pinfo->p_uutime_sec * SIGAR_MSEC;
                      ~~~~~^
../../src/os/darwin/sigar_os.h:49:16: note: forward declaration of 'struct kinfo_proc2'
typedef struct kinfo_proc2 bsd_pinfo_t;
               ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
*** Error 1 in /home/diaspora/.gem/ruby/2.6/gems/kostya-sigar-2.0.10/bindings/ruby (Makefile:245 'darwin_sigar.o': @ cc -I. -I/usr/local/inc...)
Failed to make
rake aborted!
LocalJumpError: break from proc-closure
/home/diaspora/.gem/ruby/2.6/gems/kostya-sigar-2.0.10/Rakefile:62:in `block in <top (required)>'
/usr/local/bin/rake26:23:in `load'
/usr/local/bin/rake26:23:in `<main>'
Tasks: TOP => build
(See full trace by running task with --trace)

**Comment by kostya** [comment]
i have no idea, for me looks like unfixable

**Comment by kostya** [comment]
probably you can try to remove all bugged code and probably it would be ok, because eye not used much methods.
